/**
 * agent-store.mjs — File-based Agent Registry persistence
 *
 * Single source of truth for agent configs:
 *   agents/<uuid>.json — one JSON file per agent
 *
 * This store is the TaskStore successor (concepts unified): a persisted
 * "agent" carries its rules, allowed tools, optional cron schedule, notify
 * target, and cooldown. Scheduling/notify execution live elsewhere — this
 * module is pure data persistence with schema validation.
 *
 * Design notes (TASK-001 SA review, ADR-003):
 * - Only 4 functions are exported: listAgents, getAgent, saveAgent, deleteAgent.
 * - Validation failures throw plain Error — no HTTP concepts in this layer.
 * - ids are generated by the store (randomUUID); callers cannot set them.
 * - External ids get double protection: filename whitelist regex
 *   + safeResolve() imported from tool-loader.mjs (not duplicated).
 * - Reads are asymmetric by design: listAgents skips unreadable files
 *   (warn, so one bad file can't blank the registry) while getAgent throws
 *   on a corrupt file (fail loudly on a specific read).
 * - SRE_AGENTS_DIR env var can relocate the directory (tests point it at a
 *   temp dir). Absolute values are trusted because env vars are operator
 *   config, not user input — same trust level as config.mjs env handling.
 */

import { existsSync, readFileSync, writeFileSync, renameSync, unlinkSync, mkdirSync, readdirSync } from "fs";
import { randomUUID } from "crypto";
import { isAbsolute } from "path";
import { ROOT } from "./config.mjs";
import { safeResolve } from "./tool-loader.mjs";
import { toolRegistry } from "./tool-registry.mjs";

/**
 * @typedef {import("./task-store.mjs").AgentRules} AgentRules
 */

/**
 * @typedef {Object} Agent
 * @property {string} id                            - UUID, generated by the store on create
 * @property {string} name                          - Human-readable name (1..100 chars after trim)
 * @property {string} description                   - Optional, defaults ""
 * @property {string} context                       - Optional, defaults ""
 * @property {AgentRules} agentRules                - { guardrails[], redirectRules[], refuseTopics[] }
 * @property {string} prompt                        - Optional system/role prompt, defaults ""
 * @property {string[]} allowedTools                - Tool names, defaults [] (warn on unknown, never blocked)
 * @property {string|null} schedule                 - 5-field cron expression, or null for manual-only
 * @property {Object} notifyTarget                  - Where results are sent
 * @property {"user"|"channel"} notifyTarget.targetType
 * @property {string} notifyTarget.targetId         - Non-empty string
 * @property {number} cooldownMinutes               - Positive integer, defaults 30
 * @property {boolean} enabled                      - Defaults true
 * @property {string} createdAt                     - ISO timestamp, store-owned
 * @property {string} updatedAt                     - ISO timestamp, store-owned
 */

const NAME_MAX_LENGTH = 100;
const DEFAULT_COOLDOWN_MINUTES = 30;

/** Whitelist for agent ids used as filenames (first layer of traversal defense). */
const FILENAME_SAFE_RE = /^[a-zA-Z0-9_-]+$/;
/** Only files shaped like `<safe-id>.json` are treated as agents (excludes `*.json.tmp`, README.md, dotfiles). */
const AGENT_FILE_RE = /^[a-zA-Z0-9_-]+\.json$/;

/**
 * Min/max bounds per cron field (5-field standard cron, numeric only).
 * Day-of-week allows 0-7 where both 0 and 7 mean Sunday.
 */
const CRON_FIELD_BOUNDS = [
  [0, 59], // minute
  [0, 23], // hour
  [1, 31], // day of month
  [1, 12], // month
  [0, 7], // day of week
];

function resolveAgentsDir() {
  const override = process.env.SRE_AGENTS_DIR;
  if (override && isAbsolute(override)) return override;
  return safeResolve(ROOT, override || "agents");
}

const AGENTS_DIR = resolveAgentsDir();

function ensureDir(dir) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

/**
 * Validate an external agent id against the filename whitelist.
 * Combined with safeResolve() in agentFilePath() this gives double-layer
 * path traversal protection (regex rejects `..`, `/`, `\`, `%`, dots, empty).
 * @param {string} id
 * @returns {string}
 * @throws {Error} If the id is not a string of [a-zA-Z0-9_-].
 */
function assertFilenameSafeId(id) {
  if (typeof id !== "string" || !FILENAME_SAFE_RE.test(id)) {
    throw new Error(`Invalid agent id: ${JSON.stringify(id)}`);
  }
  return id;
}

/**
 * Build the on-disk path for an agent id with double traversal protection:
 * whitelist regex first, then safeResolve anchoring under AGENTS_DIR.
 * @param {string} id
 * @returns {string}
 */
function agentFilePath(id) {
  assertFilenameSafeId(id);
  return safeResolve(AGENTS_DIR, `${id}.json`);
}

/**
 * Read one agent file. Missing file → null; corrupt JSON → throws
 * (asymmetric with listAgents, which skips corrupt files).
 * @param {string} id
 * @returns {Agent|null}
 */
function readAgentFile(id) {
  const filePath = agentFilePath(id);
  if (!existsSync(filePath)) return null;
  return JSON.parse(readFileSync(filePath, "utf-8"));
}

/**
 * Validate a single cron field part: `*`, `n`, `n-m`, each optionally `/step`.
 * @param {string} part
 * @param {[number, number]} bounds - [min, max] for this field
 * @returns {boolean}
 */
function isValidCronPart(part, [min, max]) {
  const m = part.match(/^(\*|\d{1,2})(?:-(\d{1,2}))?(?:\/(\d{1,3}))?$/);
  if (!m) return false;
  const [, startRaw, endRaw, stepRaw] = m;
  if (stepRaw !== undefined && parseInt(stepRaw, 10) < 1) return false;
  if (startRaw === "*") return endRaw === undefined; // `*-5` is not valid cron
  const start = parseInt(startRaw, 10);
  if (start < min || start > max) return false;
  if (endRaw !== undefined) {
    const end = parseInt(endRaw, 10);
    if (end < start || end > max) return false;
  }
  return true;
}

/**
 * Validate a 5-field numeric cron expression: `min hour dom mon dow`.
 * Supports `*`, ranges (`1-5`), steps (`0/15`, `1-30/2`), lists (`1,15,30`).
 * Named values (JAN, mon) and Quartz extensions (`?`, 6 fields) are rejected.
 * @param {string} expr
 * @returns {boolean}
 */
function isValidCron(expr) {
  if (typeof expr !== "string") return false;
  const fields = expr.trim().split(/\s+/);
  if (fields.length !== 5) return false;
  return fields.every((field, i) => {
    if (field === "") return false;
    return field.split(",").every(part => isValidCronPart(part, CRON_FIELD_BOUNDS[i]));
  });
}

/** Optional string field: undefined/null → "", non-string → throw. */
function optionalString(value, field) {
  if (value === undefined || value === null) return "";
  if (typeof value !== "string") throw new Error(`Agent "${field}" must be a string`);
  return value;
}

/** Lenient array coercion matching task-store's agentRules handling. */
function stringArray(value) {
  return Array.isArray(value) ? value : [];
}

/**
 * Validate + normalize agent fields (id/timestamps excluded — store-owned).
 * Unknown keys are dropped on save.
 * @param {Object} raw
 * @returns {Object} Normalized agent fields without id/createdAt/updatedAt.
 * @throws {Error} On any schema violation.
 */
function normalizeAgent(raw) {
  // name: required, trimmed length 1..100
  if (typeof raw.name !== "string" || raw.name.trim().length < 1) {
    throw new Error('Agent "name" is required (non-empty string)');
  }
  if (raw.name.trim().length > NAME_MAX_LENGTH) {
    throw new Error(`Agent "name" exceeds ${NAME_MAX_LENGTH} characters`);
  }

  const notifyTarget = raw.notifyTarget;
  if (!notifyTarget || typeof notifyTarget !== "object" || Array.isArray(notifyTarget)) {
    throw new Error('Agent "notifyTarget" is required: { targetType: "user"|"channel", targetId: string }');
  }
  if (notifyTarget.targetType !== "user" && notifyTarget.targetType !== "channel") {
    throw new Error(
      `Agent "notifyTarget.targetType" must be "user" or "channel" (got ${JSON.stringify(notifyTarget.targetType)})`
    );
  }
  if (typeof notifyTarget.targetId !== "string" || notifyTarget.targetId.trim().length < 1) {
    throw new Error('Agent "notifyTarget.targetId" must be a non-empty string');
  }

  const cooldownMinutes = raw.cooldownMinutes ?? DEFAULT_COOLDOWN_MINUTES;
  if (typeof cooldownMinutes !== "number" || !Number.isInteger(cooldownMinutes) || cooldownMinutes < 1) {
    throw new Error(`Agent "cooldownMinutes" must be a positive integer (got ${JSON.stringify(raw.cooldownMinutes)})`);
  }

  const schedule = raw.schedule ?? null;
  if (schedule !== null && (typeof schedule !== "string" || !isValidCron(schedule))) {
    throw new Error('Agent "schedule" must be a valid 5-field cron expression or null');
  }

  const allowedTools = raw.allowedTools ?? [];
  if (!Array.isArray(allowedTools) || allowedTools.some(t => typeof t !== "string")) {
    throw new Error('Agent "allowedTools" must be an array of tool name strings');
  }
  // Registry check: warn but never block — tools may be registered later or by another provider set.
  for (const toolName of allowedTools) {
    if (!toolRegistry.get(toolName)) {
      console.warn(`[agent-store] allowedTools references unregistered tool "${toolName}" — saved anyway`);
    }
  }

  const enabled = raw.enabled ?? true;
  if (typeof enabled !== "boolean") {
    throw new Error('Agent "enabled" must be a boolean');
  }

  return {
    name: raw.name,
    description: optionalString(raw.description, "description"),
    context: optionalString(raw.context, "context"),
    prompt: optionalString(raw.prompt, "prompt"),
    agentRules: {
      guardrails: stringArray(raw.agentRules?.guardrails),
      redirectRules: stringArray(raw.agentRules?.redirectRules),
      refuseTopics: stringArray(raw.agentRules?.refuseTopics),
    },
    allowedTools,
    schedule,
    notifyTarget: { targetType: notifyTarget.targetType, targetId: notifyTarget.targetId },
    cooldownMinutes,
    enabled,
  };
}

/**
 * List all agents, sorted by createdAt ascending (oldest first).
 * Tolerant read: missing dir → [], corrupt JSON → warn + skip.
 * Non-agent files (`*.json.tmp`, README.md, dotfiles) are ignored.
 * @returns {Agent[]}
 */
export function listAgents() {
  if (!existsSync(AGENTS_DIR)) return [];
  const agents = [];
  for (const file of readdirSync(AGENTS_DIR)) {
    if (!AGENT_FILE_RE.test(file)) continue;
    const filePath = safeResolve(AGENTS_DIR, file);
    try {
      agents.push(JSON.parse(readFileSync(filePath, "utf-8")));
    } catch (err) {
      console.warn(`[agent-store] Skipping unreadable agent file "${file}": ${err.message}`);
    }
  }
  return agents.sort((a, b) => (a.createdAt || "").localeCompare(b.createdAt || ""));
}

/**
 * Get a single agent by id.
 * Missing → null. Corrupt file → throws (specific reads fail loudly).
 * @param {string} id
 * @returns {Agent|null}
 * @throws {Error} On invalid/traversal id or corrupt JSON.
 */
export function getAgent(id) {
  return readAgentFile(id);
}

/**
 * Create (no id) or update (id present) an agent.
 *
 * Update semantics: partial patch merged over the stored agent; only
 * updatedAt changes, createdAt is preserved. Updating a non-existent id
 * throws with 404-flavored wording for the route layer to map.
 *
 * Atomic write: content is written to `<id>.json.tmp` then renameSync'd
 * over the final path. rename is atomic on POSIX/NTFS within a directory,
 * so a concurrent reader never sees a half-written file, and a crash
 * mid-write leaves only a `.tmp` file that listAgents ignores.
 *
 * The store owns id/createdAt/updatedAt — caller-supplied values for these
 * (and any unknown keys) are ignored.
 *
 * @param {Object} input - Agent fields; `id` present means update.
 * @returns {Agent} The stored agent.
 * @throws {Error} On schema violation, invalid id, or update of missing agent.
 */
export function saveAgent(input) {
  if (!input || typeof input !== "object" || Array.isArray(input)) {
    throw new Error("saveAgent expects an agent object");
  }

  const isUpdate = input.id !== undefined && input.id !== null;
  let base = null;
  if (isUpdate) {
    base = readAgentFile(input.id);
    if (!base) throw new Error(`Agent not found: ${input.id}`);
  }

  // Strip store-owned fields so callers cannot override them.
  const { id: _id, createdAt: _createdAt, updatedAt: _updatedAt, ...fields } = input;

  // agentRules merges per-key on update (mirrors task-store update semantics):
  // a patch with only `guardrails` keeps the stored redirectRules/refuseTopics.
  if (base && fields.agentRules && typeof fields.agentRules === "object" && !Array.isArray(fields.agentRules)) {
    fields.agentRules = {
      guardrails: fields.agentRules.guardrails ?? base.agentRules?.guardrails,
      redirectRules: fields.agentRules.redirectRules ?? base.agentRules?.redirectRules,
      refuseTopics: fields.agentRules.refuseTopics ?? base.agentRules?.refuseTopics,
    };
  }

  const normalized = normalizeAgent(base ? { ...base, ...fields } : fields);

  const now = new Date().toISOString();
  const agent = {
    ...normalized,
    id: base ? base.id : randomUUID(),
    createdAt: base ? base.createdAt : now,
    updatedAt: now,
  };

  ensureDir(AGENTS_DIR);
  const filePath = safeResolve(AGENTS_DIR, `${agent.id}.json`);
  const tmpPath = `${filePath}.tmp`;
  writeFileSync(tmpPath, JSON.stringify(agent, null, 2));
  renameSync(tmpPath, filePath);
  return agent;
}

/**
 * Delete an agent by id.
 * @param {string} id
 * @returns {boolean} true if deleted, false if not found (never throws for missing).
 * @throws {Error} On invalid/traversal id.
 */
export function deleteAgent(id) {
  const filePath = agentFilePath(id);
  if (!existsSync(filePath)) return false;
  unlinkSync(filePath);
  return true;
}
